spring:
  application:
    name: cursoapp

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

server:
  port: ${SERVER_PORT}